openapi: 3.0.3
info:
  title: Me and My Planet (Mock) API
  description: Mock API for Me and My Planet
  version: 0.0.2
servers:
  - url: https://mmp-mockapi.pantek.app
  - url: http://localhost:8080
paths:
  /myData/groupInfo:
    get:
      summary: Request information about the group the user is part of
      tags:
        - data queries
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: User group information. If user is not part of a group, an empty body is sent.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  name:
                    type: string
                    maxLength: 128
                  periodStart:
                    type: string
                    format: date
                    maxLength: 10
                  periodEnd:
                    type: string
                    format: date
                    maxLength: 10
        default:
          description: "Error String"
          content:
            text/plain:
              schema:
                type: string
                pattern: '^[A-Za-z0-9]+$'
                maxLength: 255


  /myData/byCategory/{categoryID}:
    get:
      summary: Request user data of a certain category
      tags:
        - data queries
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: categoryID
          description: ID of category to query
          required: true
          schema:
            type: number
          example: 17
      responses:
        '200':
          description: array of user data for selected category across all dates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataItem'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                type: object
                properties: { }

  /myData/byDate/{dateString}:
    get:
      summary: Request user data of a certain category
      tags:
        - data queries
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: dateString
          description: date in ISO-8601 Format
          required: true
          schema:
            type: string
          example: 2024-11-22
      responses:
        '200':
          description: array of user data for selected date across all categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataItem'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                type: object
                properties: { }

  /myData/addDaily:
    post:
      summary: Add data to database
      tags:
        - data queries
      operationId: addDaily
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewDailyData"
      responses:
        '200':
          description: Successfully added new data
          content:
            application/json:
              schema:
                type: object
                properties:
                  lastID:
                    type: number
                    example: 12
                    description: ID of last newly created data entry
        '400':
          description: Error while adding data
          content:
            application/json:
              schema:
                type: object
                properties: { }

  /myData/editDaily/{entryID}:
    post:
      summary: Edit existing data in database by entry ID
      tags:
        - data queries
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: entryID
          schema:
            type: number
          required: true
          description: ID of entry to edit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeDailyData"
      responses:
        '200':
          description: Successfully update the data
        '400':
          description: Error while updating data

  /myData/removeDaily/{entryID}:
    get:
      summary: Remove existing daily tracker entry
      tags:
        - data queries
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: entryID
          schema:
            type: number
          required: true
          description: ID of entry to edit
      responses:
        200:
          description: Entry successfully removed
        400:
          description: Error when trying to remove entry

  /myData/listFlights:
    get:
      summary: List all flights for this user
      tags:
        - data queries
      security:
        - bearerAuth: [ ]

      responses:
        '200':
          description: Successfully added new data
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/FlightItemResponse'
        '400':
          description: Error while reading data
          content:
            application/json:
              schema:
                type: object
                properties: { }

  /myData/addFlight/{date}/{originCode}/{destinationCode}/{class}:
    get:
      summary: Add flight to database
      tags:
        - data queries
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: date
          required: true
          schema:
            type: string
        - in: path
          name: originCode
          required: true
          schema:
            type: string
            maxLength: 3
        - in: path
          name: destinationCode
          required: true
          schema:
            type: string
            maxLength: 3
        - in: path
          name: class
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successfully added new data
          content:
            application/json:
              schema:
                type: object
                properties: { }
        '400':
          description: Error while adding data
          content:
            application/json:
              schema:
                type: object
                properties: { }

  /myData/editFlight/{flightID}:
    post:
      summary: Edit flight in database
      tags:
        - data queries
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: flightID
          required: true
          schema:
            type: number
          description: The ID of the flight to edit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlightItemResponse"
      responses:
        '200':
          description: Successfully added new data
        '400':
          description: Error while adding data

  /myData/removeFlight/{flightID}:
    get:
      summary: Remove flight from database
      tags:
        - data queries
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: flightID
          required: true
          schema:
            type: number
          description: The ID of the flight to remove
      responses:
        '200':
          description: Successfully added new data
          content:
            application/json:
              schema:
                type: object
                properties: { }
        '400':
          description: Error while adding data
          content:
            application/json:
              schema:
                type: object
                properties: { }

  /schema/categories:
    get:
      summary: Request category metadata
      tags:
        - schema queries
      responses:
        '200':
          description: array of category metadata
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategorySchema'

  /schema/items:
    get:
      summary: Request items metadata
      tags:
        - schema queries
      responses:
        '200':
          description: array of item metadata
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemSchema'

  /schema/units:
    get:
      summary: Request units metadatamock-password
      tags:
        - schema queries

      responses:
        '200':
          description: array of units metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 0
                  name:
                    type: string
                    example: km
                  numeric:
                    type: boolean
                    description: If numeric is 0, the amount must be determined using unit options.

  /schema/unitOptions:
    get:
      summary: Request unitOptions metadata
      tags:
        - schema queries

      responses:
        '200':
          description: array of unitOptions metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 0
                  unit:
                    type: number
                    example: 0
                    description: This is the ID of the unit this item is measured in.
                  optionsLabel:
                    type: string
                    example: small
                  value:
                    type: number
                    description: The amount this unit option equals to

  /auth/{loginType}/{userName}/{credentials}:
    get:
      summary: User authorization
      tags:
        - authorization
      parameters:
        - in: path
          name: loginType
          required: true
          schema:
            type: string
          examples:
            local-login:
              value: local
            switch-edu-login:
              value: switch
            google-login:
              value: google

        - in: path
          name: userName
          required: true
          schema:
            type: string
          example: manuela.muster@students.bfh.ch
        - in: path
          name: credentials
          description: Format of credentials heavily depends on login type, e.g., password vs SSO-token.
          required: true
          schema:
            type: string
          examples:
            local-login:
              value: mock-password
      responses:
        '200':
          description: auth successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    JWT:
                      type: string

components:
  schemas:
    Error:
      type: string
    DataItem:
      type: object
      properties:
        date:
          type: string
          format: date
          example: 2024-11-22
        amount:
          type: number
          example: 3.8
        itemID:
          type: number
          example: 17

    CategorySchema:
      type: object
      properties:
        id:
          type: number
          description: Category ID
          example: 24
        name:
          type: string
          example: Meat Products

        comment:
          type: string
          example: Products primarily containing animal meat

        parent:
          type: number
          description: ID of parent category, -1 is no parent category exists
          example: 21

    ItemSchema:
      type: object
      properties:
        name:
          type: string
          example: Coffee
        comment:
          type: string
          example: Average coffee without further specification
        unit:
          type: string
          example: cups
        category:
          type: number
          example: 12
        kgco2perunit:
          type: number
          example: 0.23

    NewDailyData:
      type: object
      properties:
        date:
          type: string
        amountNumeric:
          type: number
          minimum: 0
        amountOption:
          type: number
          minimum: 0
        itemID:
          type: number

    ChangeDailyData:
      type: object
      properties:
        id:
          type: number
          minimum: 0
        amountNumeric:
          type: number
          minimum: 0
        amountOption:
          type: number
          minimum: 0

    FlightItemResponse:
      type: object
      additionalProperties: false
      required:
        - flightID
        - date
        - origin
        - destination
        - class
        - co2eq
      properties:
        flightID:
          type: number
          minimum: 0
        user:
          type: number
        date:
          type: string
          format: date
          maxLength: 10
        origin:
          type: string
        destination:
          type: string
        class:
          type: number
        co2eq:
          type: number
        kilometer:
          type: number
        ubp:
          type: number

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT